In [1]:
import pandas as pd
dataset=pd.read_csv("Placement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [2]:
#Frequency
dataset["ssc_p"].value_counts()

ssc_p
62.00    11
63.00    10
67.00     9
52.00     9
73.00     9
         ..
69.70     1
80.92     1
83.00     1
86.50     1
80.60     1
Name: count, Length: 103, dtype: int64

In [3]:
dataset["ssc_p"].value_counts().index

Index([ 62.0,  63.0,  67.0,  52.0,  73.0,  74.0,  65.0,  69.0,  77.0,  58.0,
       ...
        81.7,  64.6,  52.6, 84.86,  75.0,  69.7, 80.92,  83.0,  86.5,  80.6],
      dtype='float64', name='ssc_p', length=103)

In [5]:
dataset["ssc_p"].value_counts().values

array([11, 10,  9,  9,  9,  7,  7,  7,  6,  6,  4,  4,  4,  4,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  2,  2,  2,  2,  2,  2,  2,  2,  2,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1])

In [8]:
dataset["ssc_p"].value_counts().sort_index

<bound method Series.sort_index of ssc_p
62.00    11
63.00    10
67.00     9
52.00     9
73.00     9
         ..
69.70     1
80.92     1
83.00     1
86.50     1
80.60     1
Name: count, Length: 103, dtype: int64>

In [19]:
df_frequency=pd.DataFrame(columns=["Unique_Values","Frequency", "Relative_Frequency","Cumulative_Frequency"])
df_frequency

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative_Frequency, Cumulative_Frequency]
Index: []

In [22]:
df_frequency["Unique_Values"]=dataset["ssc_p"].value_counts().index
df_frequency["Frequency"]=dataset["ssc_p"].value_counts().values
df_frequency["Relative_Frequency"]=(df_frequency["Frequency"] / 103)
df_frequency["Cumulative_Frequency"]=df_frequency["Relative_Frequency"].cumsum()

In [23]:
df_frequency

     Unique_Values  Frequency  Relative_Frequency  Cumulative_Frequency
0            62.00         11            0.106796              0.106796
1            63.00         10            0.097087              0.203883
2            67.00          9            0.087379              0.291262
3            52.00          9            0.087379              0.378641
4            73.00          9            0.087379              0.466019
..             ...        ...                 ...                   ...
98           69.70          1            0.009709              2.048544
99           80.92          1            0.009709              2.058252
100          83.00          1            0.009709              2.067961
101          86.50          1            0.009709              2.077670
102          80.60          1            0.009709              2.087379

[103 rows x 4 columns]

In [24]:
def frequency_table(columnName,dataset):
    df_frequency=pd.DataFrame(columns=["Unique_Values","Frequency", "Relative_Frequency","Cumulative_Frequency"])
    df_frequency["Unique_Values"]=dataset[columnName].value_counts().index
    df_frequency["Frequency"]=dataset[columnName].value_counts().values
    df_frequency["Relative_Frequency"]=(df_frequency["Frequency"] / 103)
    df_frequency["Cumulative_Frequency"]=df_frequency["Relative_Frequency"].cumsum()
    return df_frequency

In [26]:
frequency_table("ssc_p", dataset)

     Unique_Values  Frequency  Relative_Frequency  Cumulative_Frequency
0            62.00         11            0.106796              0.106796
1            63.00         10            0.097087              0.203883
2            67.00          9            0.087379              0.291262
3            52.00          9            0.087379              0.378641
4            73.00          9            0.087379              0.466019
..             ...        ...                 ...                   ...
98           69.70          1            0.009709              2.048544
99           80.92          1            0.009709              2.058252
100          83.00          1            0.009709              2.067961
101          86.50          1            0.009709              2.077670
102          80.60          1            0.009709              2.087379

[103 rows x 4 columns]